### ISSUE TITLE
IMA3 custom playback upgrade 

### ISSUE THREAD

**Issue by jfurnari** [kaltura/mwEmbed#1003]
Google is releasing changes to their IMA3 SDK for HTML5 on Sept 30th. Will this impact users of the Doubleclick plugin?

https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/guides/custom_playback

**Comment by OrenMe** [comment]
Hi @jfurnari this haven't had an impact and IMA SDK integration is working. Thanks.
