### ISSUE TITLE
doubleClick Google ads missing duration param

### ISSUE THREAD

**Issue by Roycohen** [kaltura/mwEmbed#1036]
Hi,

I'm trying to integrate Google ads with doubleClick but there is an exception.
"Uncaught TypeError: Cannot read property 'duration' of undefined"

Sample page:
http://video.panda-os.com/index.php/extwidget/preview/partner_id/123/uiconf_id/11601733/entry_id/0_vzx398p7/embed/auto?&flashvars%5BstreamerType%5D=auto

It will be really appreciated to get a solution.

**Comment by OrenMe** [comment]
Hi @lelikg  - closing due to inactive, please reach out if you still require assistance.
