### ISSUE TITLE
Enable Google Analytic from Web and Mobile

### ISSUE THREAD

**Issue by suhastnex** [kaltura/mwEmbed#1050]
Hello,

I have kaltura running on mobile application and website as per Google Analytic we have to create to different accounts for capturing data from mobile and web see attached image. Please can you suggest how can I integrate KMC to show analytic data combined from both the platforms. 

![google analytics](https://cloud.githubusercontent.com/assets/6285938/4571716/3aafe768-4f7c-11e4-8377-b79e49f7b7ac.png)

Thanks

**Comment by OrenMe** [comment]
Hi @suhastnex  - closing due to inactive, please reach out if you still require assistance.
