### ISSUE TITLE
Custom Plugin not working

### ISSUE THREAD

**Issue by ElGabbu** [kaltura/mwEmbed#1204]
So we would like to create a custom plugin in Kaltura 9.19.4 in the HTML5 player v2.18.5

We followed the instructions specified here : http://html5video.org/wiki/Kaltura_InPlayer_HTML5_Plugins

We added the XML: `<Plugin id="fooBar" width="0%" height="0%" includeInLayout="false" loadingPolicy="onDemand" 
        iframeHTML5Js1="http://xxxxxx.com/html5/myfooBarHtml5IframePlugin.js"
/>`

Then we put some alerts in various parts of the plugin skeleton but none of them triggered. 

We have also tried  clearing the cache in /opt/kaltura/app/cache/html5/ but still the alerts did not trigger.

**Comment by OrenMe** [comment]
Hi @ElGabbu - closing due to inactive, please reach out if you still require assistance.
