### ISSUE TITLE
video not filling player Issue with mwEmbed 2.22

### ISSUE THREAD

**Issue by jeansalim** [kaltura/mwEmbed#1264]
I have and issue with full screen, it only happens with playlists. It's like it considers the playlist is still there and leaves room for it.
I found that the issue is related to div.videoHolder style height not being 100%:
<div class="videoHolder" style="height: 261px;">

Here's a screenshot:
![video](https://cloud.githubusercontent.com/assets/8594395/5335846/e8182b50-7eba-11e4-932d-b03acf2e71bf.png)

**Comment by itaykinnrot** [comment]
can you share a link?

**Comment by OrenMe** [comment]
Closing due to inactive.
