### ISSUE TITLE
2.25 wont play full video using KS (when it has payperview)

### ISSUE THREAD

**Issue by AquileaSFX** [kaltura/mwEmbed#1489]
previous versions of the player
plays the full video when it has the right KS,

but with 2.25 no matter if it has the ks, it will play the video
as marked in the "payperview" acces control and the (freePreviewEnd) will trigger also, 
no matter if it has the KS

**Comment by itaykinnrot** [comment]
Can you add a link?

**Comment by AquileaSFX** [comment]
Hello,

yes I have a link,

free version 5 seconds:
http://aquileasfx.com/demos/kaltura/free.php

full version using 2.25:
http://aquileasfx.com/demos/kaltura/full.php

**Comment by jessp01** [comment]
Hey Bryan,

Does it still happen with latest? Thanks,

**Comment by jessp01** [comment]
@AquileaSFX, I am closing this one but if you are still having issues with the latest, please let us know.
