### ISSUE TITLE
Centos7.0 kaltura deployment error

### ISSUE THREAD

**Issue by indraindu** [kaltura/mwEmbed#1495]
HI,

     FOr centos6.0 some instances need yum-epel ,yum to run and install kaltura from yum-repo.When installing klatura for centos 7 and centos5.6 platform it shows like this:

[Error while installing kaltura: Mixlib::ShellOut::ShellCommandFailed: yum_repository[epel] (yum-epel::default line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[yum-makecache-epel] (/var/chef-solo/cookbooks/yum/providers/repository.rb line 49) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1' ---- Begin output of yum -q makecache --disablerepo=* --enablerepo=epel ---- STDOUT: STDERR: One of the configured repositories failed (Unknown), and yum doesn't have enough cached data to continue. At this point the only safe thing yum can do is fail. There are a few ways to work 'fix' this: 1. Contact the upstream for the repository and get them to fix the problem. 2. Reconfigure the baseurl/etc. for the repository, to point to a working upstream. This is most often useful if you are using a newer distribution release than is supported by the repository (and the packages for the previous distribution release still work). 3. Disable the repository, so yum won't use it by default. Yum will then just ignore the repository until you permanently enable it again or use --enablerepo for temporary usage: yum-config-manager --disable 4. Configure the failing repository to be skipped, if it is unavailable. Note that yum will try to contact the repo. when it runs most commands, so will have to try and fail each time (and thus. yum will be be much slower). If it is a very temporary problem though, this is often a nice compromise: yum-config-manager --save --setopt=.skip_if_unavailable=true Cannot find a valid baseurl for repo: epel ---- End output of yum -q makecache --disablerepo=* --enablerepo=epel ---- Ran yum -q makecache --disablerepo=* --enablerepo=epel returned 1]

FOr centos6.5 when updating yum update it shows like this:

[root@vm-140adf5f chef-solo]# yum update
Loaded plugins: fastestmirror, security
Determining fastest mirrors
 * epel: mirror.symnds.com
Kaltura                                                                                                                  | 2.9 kB     00:00     
Kaltura/primary_db                                                                                                       | 182 kB     00:00     
Kaltura-noarch                                                                                                           | 2.9 kB     00:00     
Kaltura-noarch/primary_db                                                                                                |  17 kB     00:00     
Kaltura-testing                                                                                                          | 2.9 kB     00:00     
Kaltura-testing/primary_db                                                                                               | 182 kB     00:00     
Kaltura-testing-noarch                                                                                                   | 2.9 kB     00:00     
Kaltura-testing-noarch/primary_db                                                                                        |  17 kB     00:00     
http://mirrors.nephoscale.com/centos/6/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirrors.nephoscale.com/centos/6/os/x86_64/repodata/repomd.xml: (28, 'connect() timed out!')
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again

Regards,
Indu

**Comment by jessp01** [comment]
For 7, you need to use a different repo, see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.4.0/doc/install-kaltura-redhat-based.md#note-on-rhelcentos-7

Thanks,
