### ISSUE TITLE
VPAID Overlay not triggered on HTML5 Player (Mobile Only)

### ISSUE THREAD

**Issue by ocundale** [kaltura/mwEmbed#1563]
I have setup a simple demo here which works perfectly on desktop, with the overlay appearing after ~5 seconds:
http://coullwebsdk.herokuapp.com/minimal-test.php

However, the same demo does not work on mobile devices such as Android devices. The reason for this seems to be that the 'overlayUrl' (as specified in the kWidget embed code) is not hit at the specified time.
Interestingly, if you pause the video and then hit play again, the creative will then load and the overlay appears. Let me know if you require any further details!
Cheers :)

**Comment by ocundale** [comment]
Also- It may save you some time to know that you can easily reproduce this using Chromes Mobile Device Emulation from the Developer Tools console.

**Comment by amirch1** [comment]
Thanks a lot! This is a bug and we will fix it for the next version.

**Comment by ocundale** [comment]
Brilliant, thanks for the update amirch!

**Comment by jessp01** [comment]
Closing issue. Thanks again @ocundale
