### ISSUE TITLE
VPAID IFrame deleted after overlay ad displayed on HTML5 Player

### ISSUE THREAD

**Issue by ocundale** [kaltura/mwEmbed#1564]
The issue can be seen on this demo page I created: http://coullwebsdk.herokuapp.com/minimal-test.php

Kaltura loads our VPAID javascript creative into an iframe within a div with ID: 'player_vpaid'.
The javascript runs fine initially-  initAd is fired, then startAd and the overlay is displayed.

However, about 3-5 seconds after the ad is displayed, the div with ID 'player_vpaid' is deleted, along with our iframe and javascript within it. Hence, we can no longer respond to events such as stopAd and the close button etc no longer functions without the javascript.

**Comment by valayDave** [comment]
How did you fix this. I am facing the same issue. Its loading my code in a friendly iframe. and the subsequently destroying the iframe.

**Comment by ocundale** [comment]
Hi Dave, it was a long time ago so can't remember exactly, but it could have been that I was trying to display an overlay ad using a preroll embed...It wasn't a problem with Katlura - I fixed the overlay demo I posted and it still works fine, so you can just copy the embed code from the source and add your tag in - let me know if you need any help :)
