### ISSUE TITLE
HTML5 Player does not call VPAID 'pauseAd' when pausing content

### ISSUE THREAD

**Issue by ocundale** [kaltura/mwEmbed#1586]
This issue can be seen on the test page here:
coullwebsdk.herokuapp.com/minimal-test.php

Wait for an overlay to appear, then pause player- Expected functionality is that the overlay should be hidden on pause and re-appear when you resume. 
However, 'pauseAd' & 'resumeAd' are not currently called.

From VPAID spec:
"pauseAd is called to pause ad playback. The ad sends an AdPaused event when the
ad has been paused. resumeAd is called to continue ad playback following a call to pauseAd. The ad sends an AdPlaying event when the ad has resumed playing."

**Comment by amirch1** [comment]
Thanks! This will be added to the next player version (2.29)

**Comment by ocundale** [comment]
Brill, let me know once you have a PR, I can test before merge if you like :)

**Comment by ocundale** [comment]
This is now working in version 2.2.9. :+1:
