### ISSUE TITLE
Flash VPAID hidden

### ISSUE THREAD

**Issue by cmoreau** [kaltura/mwEmbed#1588]
Hello,

I have a problem with your player whereas my VPAID works with others players. Indeed, when my VPAID is loaded (it's a nested VPAID: my VPAID call another VPAID which load the ad), I can hear the sound of ad but I don't see in the player. But if I click to open full screen, I see the ad, and when I close the full screen, the ad still appears in the player.

Maybe, this problem is already known by your team ? If you want I can send my VPAID in private.

Thanks for your help,
Cyrille.

Kaltura player version : 3.9.9 (Flash)

**Comment by jessp01** [comment]
Hello,

The KDP flash player is obsolete and we highly recommend the use of the HTML player [in fact, you have posted to the repository where HTML5 player resides].

Does this happen to you with HTML5 as well?

**Comment by cmoreau** [comment]
Hello and thanks for your reply. Oups I'm sorry, I thought it was the same player. My problem is my VPAID supports only Flash players (it's a .swf) so I can't test it with the new HTML5 player ... :/ Also, I think some publishers can use the old Flash player on their website, so I think it would be better to resolve this problem.

Thanks for your help :)

**Comment by jessp01** [comment]
Hello,

Feel free to post on the kaltura-kdp repo but I must say I can't promise it will be addressed since as I mentioned, it is now considered obsolete and while it works, no bug fixes are made to it.

Thanks,
