### ISSUE TITLE
please help me issue seek not working

### ISSUE THREAD

**Issue by lamnt235** [kaltura/mwEmbed#1706]
Now, I use SDKplayer native android version relase 1.7, but I  meeting issue seeking not working, please help me findding solution with issue above. 
Thanks you so mucj!

**Comment by zoharbabin** [comment]
@lamnt235 - please provide more details, live demo url showing the issue, system specs, etc.
Thanks!

**Comment by OrenMe** [comment]
@lamnt235 we have released a new native SDK for iOS and Android.
please refer to playkit-ios or playkit-android for more info.
