### ISSUE TITLE
VAST via https in mobile not working

### ISSUE THREAD

**Issue by jaydeept9** [kaltura/mwEmbed#1837]
Hi

I have used https protocol to fetch media content, its working fine in desktop but in mobiles it is showing invalid resource

**Comment by itaykinnrot** [comment]
Hi @jaydeept9 ,
Can you add an example?

**Comment by jaydeept9** [comment]
Hey hi,
 
Thanks for your valuable reply.
 
 
I will add my scenario to this mail.
 
1). I am using nginx apache server with php implementation, and I have added https and ssl configuration too.
 
my html and php files are fetching successfully, now media files are able to fetch and play in the desktop, but through mobile the media files are not playing.
 
2). Windows phone advertisement is also not playing through IE.
 
Thanks and Regards
-Jay
 
 
 
--------- Original Message -------i-- Subject: Re: [mwEmbed] VAST via https in mobile not working (#1837)

**Comment by OrenMe** [comment]
Hi @jaydeept9 please use the IMA SDK plugin(doubleClick) for your monetization flow.
