### ISSUE TITLE
Captions Plugin Refactor, 

### ISSUE THREAD

**Issue by avivais** [kaltura/mwEmbed#254]
Current captions plugin causes several issues.

We should probably use a lightweight library such as 
http://captionatorjs.com/demo.html
Which supports webVTT, srt etc.

We also need to rebuild the menu, and remove the dependency on the "menu" plugin.

We can either build the menu ourselves (Probably preferred), or use the new built-in menu in jQuery UI
http://jqueryui.com/menu/

Estimate: 5d

**Comment by OrenMe** [comment]
there are other alternatives these days such as VTT.js or native texttrack support.
Regarding UI, we are not planning a major refactor ATM.
