### ISSUE TITLE
Caption Javascript Loading error

### ISSUE THREAD

**Issue by matteos** [kaltura/mwEmbed#273]
When using HTML5 player and dynamically loading a caption file via javascript call, following error is thrown:

TypeError: this.textSources is null

Caption is loaded via 
 kdp.setKDPAttribute('closedCaptions','ccUrl',url);
 kdp.sendNotification( 'showClosedCaptions' );

Works fine with flash.
Tested on v1.6 branch (up to 1.6.12.52)

debug
-----------------------
IframePlayerApiClient:: postMessage > setKDPAttribute : closedCaptions
IframePlayerApiClient:: postMessage > sendNotification : showClosedCaptions
iframe:KDPMapping::setKDPAttribute closedCaptions p:ccUrl v:http://[*KALTURA-CE-CAPTION-URL*] for: kplayer
iframe:mw.TimedText::setupTextSources
iframe:KDPMapping:: sendNotification > showClosedCaptions[undefined]
iframe:TimedText:: setLayoutMode: ontop ( old mode: ontop )

**Comment by jessp01** [comment]
Closing as the issue refers to very old player versions.
