### ISSUE TITLE
HLS in-stream WebVTT captions not working

### ISSUE THREAD

**Issue by lelikg** [kaltura/mwEmbed#3390]
Hi,
In-stream closed captions are not working in the player.

this is the manifest: http://ovation.bamboo-video.com/api/entry/0_bndjh4u7/flavors/playlist.m3u8

HLSJS demo is working with the hls manifest
http://video-dev.github.io/hls.js/demo/?src=http%3A%2F%2Fovation.bamboo-video.com%2Fapi%2Fentry%2F0_bndjh4u7%2Fflavors%2Fplaylist.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&dumpfMP4=false&levelCapping=-1&defaultAudioCodec=undefined

but the kaltura player is not showing captions (captions plugin is enabled and set to show in-stream captions)
http://ovation.bamboo-video.com/play/0_bndjh4u7

**Comment by dan-ziv** [comment]
@lelikg 
It's because we're working with an older version of hls.js which doesn't supports 
in band captions. 
We are considering to upgrade hls.js in our next player version.

**Comment by lelikg** [comment]
@dan-ziv thanks for the info
you guys should consider adding support for passing a custom hls.js source URL via configuration.
Same for shaka player, and other dependencies.

**Comment by OrenMe** [comment]
Hi @lelikg, thanks for the suggestion.
HLS.JS was updated to latest on player v2.60.2 and now it supports in-stream CC.
