### ISSUE TITLE
Why is shaka player disabled on Android?

### ISSUE THREAD

**Issue by lelikg** [kaltura/mwEmbed#3459]
@yairans I noticed this commit
https://github.com/kaltura/mwEmbed/commit/976f59be7b7d668cb5ad658ae924574b84430b07
Any specific reason to disable Shaka player on Android?
How can we support DRM on mobile web?

**Comment by OrenMe** [comment]
@lelikg when we integrated Shaka a while ago we noticed playback issues.
We will consider adding this to the player.

Thanks,

Oren M.

**Comment by lelikg** [comment]
@OrenMe Please also upgrade Shaka to v2.1.5 (latest version) if you can 
It solves a lot of issues.

**Comment by OrenMe** [comment]
@lelikg shaka has been updated to latest 2.1.7 in v2.60.2.
