### ISSUE TITLE
Kaltura player issue

### ISSUE THREAD

**Issue by maheshk863** [kaltura/mwEmbed#3536]
I am using the bellow code to play a Kaltura video but video not playing 

<div id="myEmbedTarget" style="width: 100%; height: 580px;" itemprop="video" itemscope itemtype="http://schema.org/VideoObject">
			
			<script src="http://13.tagframe.com/p/99/sp/9900/embedIframeJs/uiconf_id/23448171/partner_id/99"></script>
			<script>
				kWidget.embed({
					'targetId': 'myEmbedTarget',
					'wid': '_99',
					'uiconf_id' : '23448171',
					'entry_id' : '0_m5iqlomm',
					
				});
			</script>

Bellow Console Error occur:-

"Error getting sources from server. Please try again.
Unknown widget [_99]"
99:50 kWidget: Kaltura HTML5 Version: 2.60
99:61 GET http://13.tagframe.com/html5/html5lib/v2.60/mwEmbedFrame.php?&wid=_99&uiconf_id=23448171&entry_id=0_m5iqlomm&playerId=myEmbedTarget&ServiceUrl=http%3A%2F%2F13.tagframe.com&CdnUrl=http%3A%2F%2F13.tagframe.com&ServiceBase=%2Fapi_v3%2Findex.php%3Fservice%3D&UseManifestUrls=true&forceMobileHTML5=true&urid=2.60&protocol=http&callback=mwi_myEmbedTarget0 

So please help me
Thanks

**Comment by OrenMe** [comment]
Hi @maheshk863 , as the error mention this partner and widget do not exist on your instance.

**Comment by OrenMe** [comment]
Hi @maheshk863 closing this, please update if you need additional help

**Comment by maheshk863** [comment]
Hi All,

I have installed the kaltura on my self server. Kaltura Player and script
 not working with self hosted.
Thanks

**Comment by OrenMe** [comment]
Hi @maheshk863 for general help with the community edition I recommend using the kaltura community forums: https://forum.kaltura.org/
