### ISSUE TITLE
Which embed code to use ? + VAST ads not playing on HTML

### ISSUE THREAD

**Issue by joeshields-at-gruden** [kaltura/mwEmbed#360]
Hi,

I have been playing around with the various Kaltura embed methods and have had success but am still a little baffled by some of the various embed methods. I will be using a player and videos from the Kaltura KMC (not running my own install). 

I have been using the dynamic embed as described on this page: http://html5video.org/kaltura-player/docs/Embedding/kwidget, which describes dynamic embed as the preferred method to embed Kaltura video on a page. I can successfully embed a video on page using this method and the video can play most of the time on desktop and mobile. 

So my next step was to load in a VAST ad tag and play preroll ads. I have this working on desktop but am getting a parsing error with the HTML player using the exact same VAST data (loading form the same URL). I have played around with a myriad of options both within the embed code, in the KMC as well as saving the vast XML locally. Nothing seems to help and am still getting the parsing error. 

I notice Kaltura have this working perfectly on their example page: http://html5video.org/kaltura-player/docs/Embedding/kwidget. This plays perfectly on all devices, so I checked out the code for this player but it is completely different and uses meEmbed, is loading plugins etc etc, very different. Annoying. 

I have my examples at the following urls:
Dynamic Player, with VAST Preroll (desktop:working, mobile:not working - xml error): http://shapevoid.com/kaltura/
Dynamic Player, without VAST preroll (working for both): http://shapevoid.com/kaltura/index-noads.html
Dynamic Player, with Force HTML, with VAST Preroll (not working - xml error , mobile:not working - xml error): http://shapevoid.com/kaltura/html
Dynamic Player, with Force HTML, without VAST preroll (not working for both, now getting embed property error): http://shapevoid.com/kaltura/index-noads.html

Overall the playing of videos seems pretty buggy when using the HTML player. And the fact that the exmple videos (which all work fine on all devices) use a different embed code base is challenging. 

If anyone can offer any advice as to what I am doing wrong in the examples above it would be much appreciated.
Thanks

**Comment by kjt1212** [comment]
Hi mdale, I am having the exact same issue. I tried the link you have mentioned, however, when I try to see its demo the ad does not play at all. The video plays directly. I did not make any changes to the preroll url am just trying to run the demo as is. What could be the issue?
