### ISSUE TITLE
make shorter than 10 seconds as progressive download configurable

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/mwEmbed#3612]
https://github.com/kaltura/mwEmbed/blob/da3641b5f0bc9b82d648a3e24234b2bef74e333c/modules/KalturaSupport/resources/mw.KWidgetSupport.js#L1817

Will the proper solution here be to change it to something like so:
```javascript
if( playerData.meta.duration < 10 && !mw.getConfig( 'Kaltura.force10secHLS' )) {
	deviceSources = this.removeAdaptiveFlavors( deviceSources );
}
```

**Comment by OrenMe** [comment]
Hi @zoharbabin this is a workable approach.
