### ISSUE TITLE
Kaltura html5 player problem

### ISSUE THREAD

**Issue by desingraj** [kaltura/mwEmbed#419]
Hi,

I am having kaltura ce6 in my local server, I installed the html51.7.0 version in kaltura. In kmc preview and embed, I checked the option for html5 fallback so that the code like below.

<script src="http://myURL/p/101/sp/10100/embedIframeJs/uiconf_id/11170264/partner_id/101"></script>

<div id="kaltura_player_1367045600" style="width: 450px; height: 240px;"><a href="#" onclick="stop();">stop</a></p>
<script>

kWidget.embed({
  "targetId": "kaltura_player_1367045600",
  "wid": "_101",
  "uiconf_id": 11170264,
  "flashvars": {},
  "cache_st": 1367043188,
  "entry_id": "0_80n5uvz8"
});
</script>

I copied the code to simple html page and run it on a browser, now it needs to play the video using html5 player. Am I right?

But the ordinary kaltura player plays the video.

Can anyone help me in this?

Thanks in advance
Desing

**Comment by jessp01** [comment]
Closing since very old versions are referred to here, making the issue no longer relevant.
