### ISSUE TITLE
HML5 Video in IE

### ISSUE THREAD

**Issue by wiyono** [kaltura/mwEmbed#461]
Hallo,
please help me?
i use html5 video on my site, but di z-index getting problem with the dropdown menu in IE?
i have already all trying but no succes...
i see in IE use div x for playing video.

Please help me, here my site: http://www.cost-and-test.com

Thank you

**Comment by OrenMe** [comment]
Hi @wiyono issue should be solved by now, tested with 2.60.2 on IE8, although you didn't mention IE version so I can't say for sure.
