### ISSUE TITLE
can i use Kaltura for my own website?

### ISSUE THREAD

**Issue by markjo12** [kaltura/mwEmbed#473]
hi
excuse me if i probably sound stupid for asking this question.

but i plan on building a website that will allow users to upload media content including video/audio.
im really interested in kaltura htm5 player code to use it on my site but i looked everywhere and i couldnt find information about the licensing. would someone be able to maybe help me out, point me in the right direction or mybe even answer my question?

**Comment by OrenMe** [comment]
Hi @markjo12, the kaltura player has a AGPL3 license, and the much of kaltura offering can be setup via the community edition which includes the player as well.
