### ISSUE TITLE
Player Loading on HTTPS

### ISSUE THREAD

**Issue by Tape** [kaltura/mwEmbed#516]
This is more or less a point of discussion as opposed to an issue, I'd just like to see the general stance on the matter.

When a player is loaded over https and a plugin uses non-https javascript it fails to load (which is expected) depending on how the end-user's browser is set up. The player fails to load entirely if any of the plugin javascript fails to load.

I personally think it would make more sense to fail silently as the browser itself will provide a warning to the developer either way. Silent failures will also help for corner cases such as a cert expiring or plugins without SSL period and preventing the entire UX from loading.

**Comment by OrenMe** [comment]
I would generally prefer such issues to surface much quicker as they might expose some SSL issues and may reveal security breaches.
In any case, current state today is that browsers are much more strict in terms of mixed content.

**Comment by pr1ntr** [comment]
http://cdnapi.kaltura.com/p/{partner_id}/sp/{partnerId}00/embedIframeJs/uiconf_id/{uiconf_id}/partner_id/{partnerId} does not support HTTPS (its a bad cert)
