### ISSUE TITLE
Hard coded cdnapi.kaltura.com URLs 

### ISSUE THREAD

**Issue by jessp01** [kaltura/mwEmbed#574]
Hey team,

If you run:
# grep cdnapi.kaltura.com /opt/kaltura/web/html5/html5lib/ -r

You'll find a lot of hard coded URLs. These should either be place holders or, better, taken from a config file as the current situation is an issue for community && OnPrem deployments.

Thanks,

**Comment by OrenMe** [comment]
Hi @jessp01, if you run the grep excluding some paths and files which are saved on runtime you'll see the issue is mostly handled, beside the share plugin maybe.
`grep cdnapi.kaltura.com ./ -r --exclude=\*.{html,txt,log} --exclude-dir=\*cache`
