### ISSUE TITLE
autoPlay for HLS content not working

### ISSUE THREAD

**Issue by rajneeshksoni** [kaltura/mwEmbed#734]
Hi,

I have enabled the autoPlay for HLS playback.
I have used example code in FlashHLSPluginTest.html. 
When i enable autoPlay video is not displayed properly, Attached is the image.
![screenshot](https://cloud.githubusercontent.com/assets/3063645/3420750/c0ddd2a4-febf-11e3-933f-3c17fcf1f5cd.png)

``` javascript
            "kdpVars": {
                    "sourceType": "url",
                                        "autoPlay": true,
                    "ignoreStreamerTypeForSeek": "true",
                    "KalturaHLS": {
                        plugin: "true",
                        //pluginURL: '../../EmbedPlayer/binPlayers/kaltura-player/plugins/KalturaHLSPlugin.swf',
                        asyncInit: "true",
                        loadingPolicy: "preInitialize",
                        //waitForSecondLoad: "false"
                    }
                },
```

If i remove the autoPlay the playback is proper. Also autoPlay works properly for mp4 content but not for HLS.
I am using released version v2.13.rc2
I am testing it in firefox on linux.
Is this a known issue ?
How can i enable autoPlay for HLS content ?

**Comment by OrenMe** [comment]
Hi @rajneeshksoni - autoplay is working now with native HLS playback.
