### ISSUE TITLE
Jquery.colour

### ISSUE THREAD

**Issue by paladox** [kaltura/mwEmbed#773]
hi could someone fix jquery.colour.js please because mediawiki has it in its core but does not have the codes but same name so could it be renamed to something else along with the functions it uses so that mediawiki can upgrade to 2.0 and 1.9. because I have to remove jquery.colour from resourceloder in mwembedsuport. or it wont work.

**Comment by OrenMe** [comment]
Hi @paladox  - closing due to inactive, please reach out if you still require assistance.
