### ISSUE TITLE
Add support for not using java

### ISSUE THREAD

**Issue by paladox** [kaltura/mwEmbed#780]
Hi please could you change support to something else to play the video instead of using java. So that other devices can use it because tablets and mobiles do not support java. And plus it would speed everything up if we did not use java because java now blocks the video by default if not signed. so could we use a html 5 player or something else instead of java please.

**Comment by OrenMe** [comment]
Hi @paladox - although the issue is quite old, I can assure you we support mostly native playback these days with fallback to flash where native playback is not supported.
