### ISSUE TITLE
Add this ogv player 

### ISSUE THREAD

**Issue by paladox** [kaltura/mwEmbed#813]
Hi someone else has developed a ogv player capable of playing the audio or video on browser that doint support it natavily. it works on ios to. please see https://github.com/brion/ogv.js and to try it please see http://ogvjs-testing.wmflabs.org/wiki/Demo

**Comment by OrenMe** [comment]
Hi @paladox, thanks for the suggestion. I don't foresee any major upgrade to support this in mwEmbed currently. feel free to reopen if this is still an issue.
