### ISSUE TITLE
Separate concerns and add Composer support

### ISSUE THREAD

**Issue by phansys** [kaltura/mwEmbed#976]
There is any plan to separate concerns in different repos?
The whole project currently reaches more than 160mb.
It would be nice to have each feature in a separate repo in order to allow quick and lightweight install if you don't need the complete mwEmbed library.
Even better, each of this micro-projects could trust in [Composer](https://getcomposer.org/) to delegate the dependency management between each other.
In the worst case, if you don't have in mind to integrate dependency management, at least git submodules could be used.
Thank you in advance.

**Comment by OrenMe** [comment]
Hi @phansys, although this is a good approach, we unfortunately not planning to preform this kind of a major refactor to the library.
