### ISSUE TITLE
Kaltura html5 video player issue

### ISSUE THREAD

**Issue by vijayrura** [kaltura/mwEmbed#991]
Hi,
I am using kaltura html 5 video player in our code for live streaming and mp4 videos .it is working fine in all browsers on my host PC  but when i run it in Sony  blue ray disk player then it does not run, and showing me the following error:-
"An error was experienced when playing the video. Please check your internet connection and try again
![dsc_0421](https://cloud.githubusercontent.com/assets/8832909/4335711/4ed6b73a-3fff-11e4-99da-52e6738065ed.jpg)
 ";

**Comment by OrenMe** [comment]
Closing due to inactive, please reach out if you still require assistance.
